---
title: "Untitled"
author: "Lancelot Ravier"
date: "2025-02-17"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r, echo=F}
library(dplyr)
library(lubridate)
library(readr)
library(hms)
library(zoo)
library(forecast)
library(tseries)

# Importation des données

data <- read.csv("~/github/projet_electricite_temperature/data/powerconsumption.csv", header=T)

# Rassemblement des données des 3 centrales en une variable "conso"

data$conso = 
  data$PowerConsumption_Zone1+
  data$PowerConsumption_Zone2+
  data$PowerConsumption_Zone3

# Suppression des variables inutiles

data = data %>%
  select(-PowerConsumption_Zone1, -PowerConsumption_Zone2, -PowerConsumption_Zone3, -Humidity, -WindSpeed, -GeneralDiffuseFlows, -DiffuseFlows)

# Modification du format de date pour faciliter la manipulation

data$Datetime <- as.POSIXct(data$Datetime, format="%m/%d/%Y %H:%M")

# Creation d'une df pour l'été

data_ete <- data %>%
  filter(month(Datetime) == 7 | month(Datetime) == 8) %>%
  filter(minute((Datetime)) == 0) %>%
  filter(day(Datetime) <= 31)
```

# TEMPERATURE

holt winters saisonnier

```{r}
ts_temp = ts(data_ete$Temperature, frequency = 24, start = c(1,1))
decompose_temp = decompose(ts_temp)
plot(decompose_temp)
```
```{r}
ts_temp_deseason = ts_temp - decompose_temp$seasonal

t<-1:1488
t1<-ts(t,start=c(1,1),freq=24)
t2<-ts(t^2,start=c(1,1),freq=24)
lm2 = lm(ts_temp_deseason~t1+t2)

plot(ts_temp_deseason)
lines(predict(lm2), col = "blue")
```

```{r}
res_ts_temp = ts_temp_deseason - lm2$fitted.values
par(mfrow=c(1,2))
acf(res_ts_temp, main="ts_temp - est.trend", lag.max = 192)
pacf(res_ts_temp)
```
```{r}
adf.test(res_ts_temp)
kpss.test(res_ts_temp)
```
```{r}
arima_model_res = arima(res_ts_temp, order = c(1, 0, 2), seasonal = list(order = c(1, 1, 1), period = 24)) # = auto.arima()

par(mfrow=c(1,2))
acf(arima_model_res$residuals, main="serie1 csv - est. tend.", ylim = c(-1, 1))
pacf(arima_model_res$residuals, ylim = c(-1, 1))
```
```{r}
library("car")

arima_model_2 = arima(ts_temp, order = c(1, 0, 2), seasonal = list(order = c(1, 1, 1), period = 24)) # = auto.arima()
arima_model_2_log = arima(log(ts_temp), order = c(1, 0, 2), seasonal = list(order = c(1, 1, 1), period = 24)) # = auto.arima()
arima_model_2_sqrt = arima(BoxCox(ts_temp, lambda = "auto"), order = c(1, 0, 2), seasonal = list(order = c(1, 1, 1), period = 24)) # = auto.arima()

par(mfrow = c(1, 3))
qqPlot(arima_model_2$residuals)
qqPlot(arima_model_2_log$residuals)
qqPlot(arima_model_2_sqrt$residuals)

```

```{r}
par(mfrow = c(1,2))
fitted_values_2 <- fitted(arima_model_2)
plot(fitted_values_2, arima_model_2$residuals, main="Résidus vs Valeurs Ajustées", 
     xlab="Valeurs Ajustées", ylab="Résidus")
abline(h=0, col="red")

fitted_values <- fitted(arima_model_2_sqrt)
plot(fitted_values, arima_model_2_sqrt$residuals, main="Résidus vs Valeurs Ajustées", 
     xlab="Valeurs Ajustées", ylab="Résidus")
abline(h=0, col="red")
```
decompose + predict + residus
```{r}
Box.test(arima_model_res$residuals, type="Ljung")
```

```{r}
auto_arima_temp <- auto.arima(ts_temp, ic = "bic")
```

```{r}
arima_model_1 = arima(ts_temp, order = c(1, 0, 2), seasonal = list(order = c(0, 0, 2), period = 24)) # = auto.arima()
```

```{r}
hw_temp <- HoltWinters(ts_temp, alpha = T, gamma = T)
ets_temp <- ets(ts_temp)
```

```{r}
auto_arima_temp <- auto.arima(ts_temp, ic = "bic")
ets_temp <- ets(ts_temp)

predict_temp <- forecast(arima_model, h = 192)
test_predict_temp <- forecast(auto_arima_temp, h = 192)
predict_temp_season <- forecast(arima_model_2, h = 192)
predict_hw_temp <- forecast(hw_temp, h = 192)
predict_ets_temp <- forecast(ets_temp, h = 192)

par(mfrow = c(1, 5))
xlim_start <- as.POSIXct("2017-09-01 00:00:00")
xlim_end <- as.POSIXct("2017-09-03 23:00:00")

plot(test_predict_temp, xlim = c(63, 66), ylim = c(10, 40), main = "SARIMA(2,0,0)(2,1,0)[24]")

plot(data$Datetime, data$Temperature, col = "red", type = "l", 
     xlim = c(xlim_start, xlim_end),
     xlab = "Temps", ylab = "Consommation électrique", 
     main = "Temperature", ylim = c(10, 40))

plot(predict_temp_season, xlim = c(63, 66), ylim = c(10, 40), main = "ARIMA(1,0,2)(0,0,2)[24]")
plot(predict_ets_temp, xlim = c(63, 66), ylim = c(10, 40), main = "ets")
plot(predict_hw_temp, xlim = c(63, 66), ylim = c(10, 40), main = "Holt Winters")

```
Erreur de prevision entre les deux
# CONSOMMATION

```{r}
# Creation de la série temporelle pour la température

ts_watt = ts(data_ete$conso, frequency = 24, start = c(1,1))
decompose_watt = decompose(ts_watt)
plot(decompose_watt)
```
```{r}
ts_watt_trend = decompose_watt$trend

t<-1:1488
t1<-ts(t,start=c(1,1),freq=24)
t2<-ts(t^2,start=c(1,1),freq=24)
t3<-ts(t^3,start=c(1,1),freq=24)
t4<-ts(t^4,start=c(1,1),freq=24)
t5<-ts(t^5,start=c(1,1),freq=24)
lm2 = lm(ts_watt_trend~t1+t2)

plot(ts_watt_trend, ylim = c(0, 500000))
lines(predict(lm2), col = "blue")
```

```{r}
par(mfrow=c(1,2))
acf(ts_watt, main="ts_watt - est.trend", lag.max = 192)
pacf(ts_watt)
adf.test(ts_watt)
```

```{r}
arima_watt_res_1 = arima(ts_watt, order = c(2, 0, 0), seasonal = list(order = c(1, 1, 1), period = 24)) # = auto.arima()

par(mfrow=c(1,2))
acf(arima_watt_res_1$residuals, main="serie1 csv - est. tend.", ylim = c(-1, 1), lag.max = 192)
pacf(arima_watt_res_1$residuals, ylim = c(-1, 1), lag.max = 192)
```

```{r}
Box.test(arima_watt_res_1$residuals, type="Ljung")
```

```{r}
par(mfrow = c(1,3))
fitted_values <- fitted(arima_watt_res_1)
plot(fitted_values, arima_watt_res_1$residuals, main="Résidus vs Valeurs Ajustées", 
     xlab="Valeurs Ajustées", ylab="Résidus")
abline(h=0, col="red")

hist(arima_watt_res_1$residuals, main = "Histogramme des résidus", probability = TRUE)
lines(density(arima_watt_res_1$residuals), col = "blue")
lines(density(rnorm(1000000)), col = "red")

qqPlot(arima_watt_res_1$residuals)
```
```{r}
auto_arima_watt <- auto.arima(ts_watt, ic = "bic", seasonal = T)
arima_watt_res_2 = arima(ts_watt, order = c(0, 0, 1), seasonal = list(order = c(0, 0, 2), period = 24)) # = auto.arima()
```

```{r}

predict_watt <- forecast(arima_watt_res_1, h = 24)
test_predict_watt <- forecast(auto_arima_watt, h = 24)

par(mfrow = c(1, 3))
xlim_start <- as.POSIXct("2017-09-01 00:00:00")
xlim_end <- as.POSIXct("2017-09-01 23:00:00")

plot(test_predict_watt, xlim = c(63, 64), ylim = c(40000, 120000))

plot(data$Datetime, data$conso, col = "red", type = "l", 
     xlim = c(xlim_start, xlim_end),
     xlab = "Temps", ylab = "Consommation électrique", 
     main = "Temperature", ylim = c(40000, 120000) )

plot(predict_watt, xlim = c(63, 64), ylim = c(40000, 120000))
```
